### ISSUE TITLE
Encoding considerations need to be syntactically valid

### ISSUE THREAD

**Issue by alvestrand** [ietf-wg-mediaman/haptics#2]
7bit, 8bit, binary and framed are the only legal choices according to Alexey.

**Comment by alvestrand** [comment]
Still an issue in -02.

**Comment by drykm** [comment]
> Still an issue in -02.

Fixed in version 03. 

Version 03 was uploaded on Feb 08, 2023: https://datatracker.ietf.org/doc/draft-ietf-mediaman-haptics/03/.

All comments welcome.
