### ISSUE TITLE
HAPT type definition needs to have a specification and vnd. prefix

### ISSUE THREAD

**Issue by alvestrand** [ietf-wg-mediaman/haptics#4]
As described, HAPT is a vendor-specific format without a published definition, and therefore belongs in the vendor tree.

The words "a logical extension of the RIFF standard" are not a reference to a published specification.

**Comment by drykm** [comment]
FIXED.

HAPT has been replaced by two MPEG standard formats, HMPG and HJIF in v04 of the haptics I-D. Available here: https://datatracker.ietf.org/doc/draft-ietf-mediaman-haptics/04/.

**Comment by alvestrand** [comment]
Thank you. Verified as fixed.
