### ISSUE TITLE
Registration needs to be according to [TOPLEVEL]

### ISSUE THREAD

**Issue by alvestrand** [ietf-wg-mediaman/haptics#5]
Since we have a new toplevel procedure, the registration procedure should reference that, not RFC 6838.

This affects section 1 and 4 of the draft.

**Comment by drykm** [comment]
Fixed in v04 of the haptics I-D. Available here: https://datatracker.ietf.org/doc/draft-ietf-mediaman-haptics/04/

**Comment by alvestrand** [comment]
Good for section 1 and section 4 (intro), which talk about the registration of a new toplevlel type.
Unfortunately the modification to section 4.2 (registration of subtypes) needs to continue to refer to 6838.

**Comment by drykm** [comment]
FIXED.

Reference in Section 4.2 has been fixed in v05. Available here: https://datatracker.ietf.org/doc/draft-ietf-mediaman-haptics/05/
